In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("INFY.csv")
df.head(5)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,1996-01-01,INFOSYSTCH,EQ,408.00,407.0,407.9,405.00,NaN,407.90,406.48,400,1.625900e+10,NaN,NaN,NaN
1,1996-01-02,INFOSYSTCH,EQ,407.90,407.0,409.0,406.25,NaN,406.25,407.58,400,1.630300e+10,NaN,NaN,NaN
2,1996-01-03,INFOSYSTCH,EQ,406.25,409.0,409.0,409.00,NaN,409.00,409.00,200,8.180000e+09,NaN,NaN,NaN
3,1996-01-04,INFOSYSTCH,EQ,409.00,405.0,407.0,405.00,NaN,406.30,405.65,600,2.433900e+10,NaN,NaN,NaN
4,1996-01-05,INFOSYSTCH,EQ,406.30,401.5,401.5,401.50,NaN,401.50,401.50,100,4.015000e+09,NaN,NaN,NaN

In [ ]:
df.columns

Index(['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble'],
      dtype='object')

In [ ]:
df.dtypes

Date                   object
Symbol                 object
Series                 object
Prev Close            float64
Open                  float64
High                  float64
Low                   float64
Last                  float64
Close                 float64
VWAP                  float64
Volume                  int64
Turnover              float64
Trades                float64
Deliverable Volume    float64
%Deliverble           float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6348 entries, 0 to 6347
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                6348 non-null   object
 1   Symbol              6348 non-null   object
 2   Series              6348 non-null   object
 3   Prev Close          6348 non-null   float64
 4   Open                6348 non-null   float64
 5   High                6348 non-null   float64
 6   Low                 6348 non-null   float64
 7   Last                5802 non-null   float64
 8   Close               6348 non-null   float64
 9   VWAP                6348 non-null   float64
 10  Volume              6348 non-null   int64
 11  Turnover            6348 non-null   float64
 12  Trades              2501 non-null   float64
 13  Deliverable Volume  4843 non-null   float64
 14  %Deliverble         4843 non-null   float64
dtypes: float64(11), int64(1), object(3)
memory usage: 744.0+ KB

In [ ]:
df1 = df[['Date','Close']]
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6348 entries, 0 to 6347
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6348 non-null   object
 1   Close   6348 non-null   float64
dtypes: float64(1), object(1)
memory usage: 99.3+ KB

In [ ]:
pred_days = 15
reward = 0
risk =1
days_shape = 75
eps = 200


df1['Xth'] = df1['Close'].shift(-1* pred_days)
print(len(df1.Close))

6348

<ipython-input-7-0750bd8be2e1>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Xth'] = df1['Close'].shift(-1* pred_days)

In [ ]:


c1 = []
for i in range(1,days_shape):
    df1['temp'] = df1['Xth'] - df1['Xth'].shift(-1*i)
    df1['temp'] = df1['temp']/df1['Xth']*100
    c1.append(df1['temp'].to_numpy())

print(c1)    
df2 = pd.DataFrame(c1)
df3 = df2.transpose()
df3.head(10)

[array([0.31446541, 0.44164038, 0.38022814, ...,        nan,        nan,
              nan]), array([0.75471698, 0.82018927, 0.95057034, ...,        nan,        nan,
              nan]), array([ 1.13207547,  1.38801262, -0.25348542, ...,         nan,
               nan,         nan]), array([ 1.69811321,  0.18927445, -1.39416984, ...,         nan,
               nan,         nan]), array([ 0.50314465, -0.94637224, -5.1964512 , ...,         nan,
               nan,         nan]), array([-0.62893082, -4.7318612 , -8.9860583 , ...,         nan,
               nan,         nan]), array([-4.40251572, -8.50473186, -8.99873257, ...,         nan,
               nan,         nan]), array([ -8.16352201,  -8.51735016, -11.53358682, ...,          nan,
                nan,          nan]), array([ -8.17610063, -11.04100946,  -8.56780735, ...,          nan,
                nan,          nan]), array([-10.6918239 ,  -8.08832808, -15.33586819, ...,          nan,
                nan,          nan]), array([ -7.74842767, -14.82649842, -19.7338403 , ...,          nan,
                nan,          nan]), array([-14.46540881, -19.20504732, -18.37769328, ...,          nan,
                nan,          nan]), array([-18.83018868, -17.85488959, -24.20785805, ...,          nan,
                nan,          nan]), array([-17.48427673, -23.65930599, -28.8973384 , ...,          nan,
                nan,          nan]), array([-23.27044025, -28.32807571, -30.11406844, ...,          nan,
                nan,          nan]), array([-27.9245283 , -29.53943218, -30.48162231, ...,          nan,
                nan,          nan]), array([-29.13207547, -29.90536278, -27.78200253, ...,          nan,
                nan,          nan]), array([-29.49685535, -27.21766562, -25.75411914, ...,          nan,
                nan,          nan]), array([-26.81761006, -25.19873817, -24.77820025, ...,          nan,
                nan,          nan]), array([-24.80503145, -24.22712934, -25.98225602, ...,          nan,
                nan,          nan]), array([-23.83647799, -25.42586751, -26.74271229, ...,          nan,
                nan,          nan]), array([-25.03144654, -26.1829653 , -20.40557668, ...,          nan,
                nan,          nan]), array([-25.78616352, -19.87381703, -20.6590621 , ...,          nan,
                nan,          nan]), array([-19.49685535, -20.12618297, -18.88466413, ...,          nan,
                nan,          nan]), array([-19.74842767, -18.35962145, -19.77186312, ...,          nan,
                nan,          nan]), array([-17.98742138, -19.24290221, -21.6730038 , ...,          nan,
                nan,          nan]), array([-18.86792453, -21.13564669, -18.25095057, ...,          nan,
                nan,          nan]), array([-20.75471698, -17.72870662, -21.6730038 , ...,          nan,
                nan,          nan]), array([-17.35849057, -21.13564669, -22.67427123, ...,          nan,
                nan,          nan]), array([-20.75471698, -22.13249211, -21.41951838, ...,          nan,
                nan,          nan]), array([-21.74842767, -20.88328076, -21.6730038 , ...,          nan,
                nan,          nan]), array([-20.50314465, -21.13564669, -18.75792142, ...,          nan,
                nan,          nan]), array([-20.75471698, -18.23343849, -21.6730038 , ...,          nan,
                nan,          nan]), array([-17.86163522, -21.13564669, -21.16603295, ...,          nan,
                nan,          nan]), array([-20.75471698, -20.63091483, -21.34347275, ...,          nan,
                nan,          nan]), array([-20.25157233, -20.80757098, -21.6730038 , ...,          nan,
                nan,          nan]), array([-20.42767296, -21.13564669, -21.29277567, ...,          nan,
                nan,          nan]), array([-20.75471698, -20.75709779, -22.8643853 , ...,          nan,
                nan,          nan]), array([-20.37735849, -22.32176656, -21.41951838, ...,          nan,
                nan,          nan]), array([-21.93710692, -20.88328076, -19.79721166, ...,          nan,
                nan,          nan]), array([-20.50314465, -19.2681388 , -20.6590621 , ...,          nan,
                nan,          nan]), array([-18.89308176, -20.12618297, -23.20659062, ...,          nan,
                nan,          nan]), array([-19.74842767, -22.66246057, -27.4904943 , ...,          nan,
                nan,          nan]), array([-22.27672956, -26.92744479, -28.01013942, ...,          nan,
                nan,          nan]), array([-26.52830189, -27.44479495, -26.99619772, ...,          nan,
                nan,          nan]), array([-27.04402516, -26.43533123, -26.74271229, ...,          nan,
                nan,          nan]), array([-26.03773585, -26.1829653 , -27.47782003, ...,          nan,
                nan,          nan]), array([-25.78616352, -26.9148265 , -33.96704689, ...,          nan,
                nan,          nan]), array([-26.51572327, -33.37539432, -41.31812421, ...,          nan,
                nan,          nan]), array([-32.95597484, -40.69400631, -39.67046895, ...,          nan,
                nan,          nan]), array([-40.25157233, -39.05362776, -41.79974651, ...,          nan,
                nan,          nan]), array([-38.6163522 , -41.17350158, -50.57034221, ...,          nan,
                nan,          nan]), array([-40.72955975, -49.90536278, -56.60329531, ...,          nan,
                nan,          nan]), array([-49.43396226, -55.91167192, -64.28390368, ...,          nan,
                nan,          nan]), array([-55.42138365, -63.55835962, -62.45880862, ...,          nan,
                nan,          nan]), array([-63.04402516, -61.74132492, -61.21673004, ...,          nan,
                nan,          nan]), array([-61.2327044 , -60.50473186, -57.41444867, ...,          nan,
                nan,          nan]), array([-60.        , -56.7192429 , -58.07351077, ...,          nan,
                nan,          nan]), array([-56.22641509, -57.37539432, -61.22940431, ...,          nan,
                nan,          nan]), array([-56.88050314, -60.51735016, -60.98859316, ...,          nan,
                nan,          nan]), array([-60.01257862, -60.27760252, -60.59569075, ...,          nan,
                nan,          nan]), array([-59.77358491, -59.88643533, -59.44233207, ...,          nan,
                nan,          nan]), array([-59.3836478 , -58.73817035, -59.8225602 , ...,          nan,
                nan,          nan]), array([-58.23899371, -59.11671924, -59.8225602 , ...,          nan,
                nan,          nan]), array([-58.6163522 , -59.11671924, -62.73764259, ...,          nan,
                nan,          nan]), array([-58.6163522 , -62.01892744, -62.80101394, ...,          nan,
                nan,          nan]), array([-61.50943396, -62.08201893, -63.85297845, ...,          nan,
                nan,          nan]), array([-61.57232704, -63.12933754, -64.76552598, ...,          nan,
                nan,          nan]), array([-62.6163522 , -64.03785489, -66.97084918, ...,          nan,
                nan,          nan]), array([-63.52201258, -66.23343849, -71.44486692, ...,          nan,
                nan,          nan]), array([-65.71069182, -70.68769716, -74.33460076, ...,          nan,
                nan,          nan]), array([-70.1509434 , -73.56466877, -74.23320659, ...,          nan,
                nan,          nan]), array([-73.01886792, -73.4637224 , -73.37135615, ...,          nan,
                nan,          nan]), array([-72.91823899, -72.60567823, -71.07731305, ...,          nan,
                nan,          nan])]

<ipython-input-8-fb2cf193e025>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['temp'] = df1['Xth'] - df1['Xth'].shift(-1*i)
<ipython-input-8-fb2cf193e025>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['temp'] = df1['temp']/df1['Xth']*100

,0,1,2,3,4,5,6,7,8,9,...,64,65,66,67,68,69,70,71,72,73
0,0.314465,0.754717,1.132075,1.698113,0.503145,-0.628931,-4.402516,-8.163522,-8.176101,-10.691824,...,-58.616352,-58.616352,-61.509434,-61.572327,-62.616352,-63.522013,-65.710692,-70.150943,-73.018868,-72.918239
1,0.441640,0.820189,1.388013,0.189274,-0.946372,-4.731861,-8.504732,-8.517350,-11.041009,-8.088328,...,-59.116719,-62.018927,-62.082019,-63.129338,-64.037855,-66.233438,-70.687697,-73.564669,-73.463722,-72.605678
2,0.380228,0.950570,-0.253485,-1.394170,-5.196451,-8.986058,-8.998733,-11.533587,-8.567807,-15.335868,...,-62.737643,-62.801014,-63.852978,-64.765526,-66.970849,-71.444867,-74.334601,-74.233207,-73.371356,-71.077313
3,0.572519,-0.636132,-1.781170,-5.597964,-9.402036,-9.414758,-11.959288,-8.982188,-15.776081,-20.190840,...,-63.422392,-64.478372,-65.394402,-67.608142,-72.099237,-75.000000,-74.898219,-74.033079,-71.730280,-73.486005
4,-1.215611,-2.367242,-6.206014,-10.031990,-10.044786,-12.603967,-9.609725,-16.442738,-20.882917,-19.513756,...,-65.425464,-66.346769,-68.573257,-73.090211,-76.007678,-75.905310,-75.035189,-72.719130,-74.484965,-71.810621
5,-1.137800,-4.930468,-8.710493,-8.723135,-11.251580,-8.293300,-15.044248,-19.431100,-18.078382,-23.893805,...,-64.348925,-66.548673,-71.011378,-73.893805,-73.792668,-72.932996,-70.644753,-72.389381,-69.747155,-67.420986
6,-3.750000,-7.487500,-7.500000,-10.000000,-7.075000,-13.750000,-18.087500,-16.750000,-22.500000,-27.125000,...,-64.675000,-69.087500,-71.937500,-71.837500,-70.987500,-68.725000,-70.450000,-67.837500,-65.537500,-66.562500
7,-3.602410,-3.614458,-6.024096,-3.204819,-9.638554,-13.819277,-12.530120,-18.072289,-22.530120,-23.686747,...,-62.975904,-65.722892,-65.626506,-64.807229,-62.626506,-64.289157,-61.771084,-59.554217,-60.542169,-60.120482
8,-0.011629,-2.337481,0.383766,-5.826259,-9.861612,-8.617281,-13.966740,-18.269566,-19.385975,-19.723224,...,-59.960461,-59.867426,-59.076637,-56.971741,-58.576579,-56.146063,-54.006280,-54.959879,-54.552855,-53.471334
9,-2.325581,0.395349,-5.813953,-9.848837,-8.604651,-13.953488,-18.255814,-19.372093,-19.709302,-17.232558,...,-59.848837,-59.058140,-56.953488,-58.558140,-56.127907,-53.988372,-54.941860,-54.534884,-53.453488,-53.720930

In [ ]:
df3.shape

(6348, 74)

In [ ]:
c2 =df3.to_numpy()
c2

array([[  0.31446541,   0.75471698,   1.13207547, ..., -70.1509434 ,
        -73.01886792, -72.91823899],
       [  0.44164038,   0.82018927,   1.38801262, ..., -73.56466877,
        -73.4637224 , -72.60567823],
       [  0.38022814,   0.95057034,  -0.25348542, ..., -74.23320659,
        -73.37135615, -71.07731305],
       ...,
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan],
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan],
       [         nan,          nan,          nan, ...,          nan,
                 nan,          nan]])

In [ ]:
len(c2)

6348

In [ ]:
c3 =[]

for i in range(int(len(c2)-days_shape)):
      
    c6 = np.concatenate((c2[i:i+days_shape]))
    
    c3.append(c6)

In [ ]:
c3[1:3]

[array([0.44164038, 0.82018927, 1.38801262, ..., 4.2181446 , 3.88186271,
        4.23276555]),
 array([ 0.38022814,  0.95057034, -0.25348542, ...,  2.59297674,
         2.94858498,  1.60023707])]

In [ ]:
df4 = pd.DataFrame(c3)
df4.head(10)

,0,1,2,3,4,5,6,7,8,9,...,5540,5541,5542,5543,5544,5545,5546,5547,5548,5549
0,0.314465,0.754717,1.132075,1.698113,0.503145,-0.628931,-4.402516,-8.163522,-8.176101,-10.691824,...,3.033389,2.378701,5.724885,7.397978,7.470721,6.357751,6.306831,4.342766,4.691933,4.357314
1,0.441640,0.820189,1.388013,0.189274,-0.946372,-4.731861,-8.504732,-8.517350,-11.041009,-8.088328,...,1.893413,5.256232,6.937642,7.010746,5.892244,5.841070,3.867242,4.218145,3.881863,4.232766
2,0.380228,0.950570,-0.253485,-1.394170,-5.196451,-8.986058,-8.998733,-11.533587,-8.567807,-15.335868,...,3.985776,5.689732,5.763817,4.630316,4.578456,2.578160,2.933768,2.592977,2.948585,1.600237
3,0.572519,-0.636132,-1.781170,-5.597964,-9.402036,-9.414758,-11.959288,-8.982188,-15.776081,-20.190840,...,6.644177,6.717512,5.595483,5.544148,3.564095,3.916104,3.578762,3.930771,2.596069,1.730713
4,-1.215611,-2.367242,-6.206014,-10.031990,-10.044786,-12.603967,-9.609725,-16.442738,-20.882917,-19.513756,...,5.265510,4.126015,4.073881,2.063007,2.420496,2.077903,2.435391,1.079914,0.201087,0.238326
5,-1.137800,-4.930468,-8.710493,-8.723135,-11.251580,-8.293300,-15.044248,-19.431100,-18.078382,-23.893805,...,2.793929,2.741071,0.702258,1.064713,0.717360,1.079816,-0.294495,-1.185532,-1.147776,-0.143472
6,-3.750000,-7.487500,-7.500000,-10.000000,-7.075000,-13.750000,-18.087500,-16.750000,-22.500000,-27.125000,...,3.339587,1.313321,1.673546,1.328330,1.688555,0.322702,-0.562852,-0.525328,0.472795,-0.615385
7,-3.602410,-3.614458,-6.024096,-3.204819,-9.638554,-13.819277,-12.530120,-18.072289,-22.530120,-23.686747,...,1.053424,1.414597,1.068473,1.429646,0.060196,-0.827690,-0.790068,0.210685,-0.880361,-1.429646
8,-0.011629,-2.337481,0.383766,-5.826259,-9.861612,-8.617281,-13.966740,-18.269566,-19.385975,-19.723224,...,0.719861,0.371297,0.735016,-0.644086,-1.538228,-1.500341,-0.492536,-1.591271,-2.144427,-4.569220
9,-2.325581,0.395349,-5.813953,-9.848837,-8.604651,-13.953488,-18.255814,-19.372093,-19.709302,-17.232558,...,0.544629,0.907716,-0.468986,-1.361573,-1.323752,-0.317700,-1.414523,-1.966717,-4.387292,-1.664145

In [ ]:
df4.shape

(6273, 5550)

In [ ]:
df1.shape

(6348, 4)

In [ ]:
aes = df1.shape[0]

In [ ]:
df4['Close'] = df1.iloc[:aes]['Close']

df4['Xth'] = df1.iloc[:aes]['Xth']
df4.shape

(6273, 5552)

In [ ]:
df3.head(5)

,0,1,2,3,4,5,6,7,8,9,...,64,65,66,67,68,69,70,71,72,73
0,0.314465,0.754717,1.132075,1.698113,0.503145,-0.628931,-4.402516,-8.163522,-8.176101,-10.691824,...,-58.616352,-58.616352,-61.509434,-61.572327,-62.616352,-63.522013,-65.710692,-70.150943,-73.018868,-72.918239
1,0.441640,0.820189,1.388013,0.189274,-0.946372,-4.731861,-8.504732,-8.517350,-11.041009,-8.088328,...,-59.116719,-62.018927,-62.082019,-63.129338,-64.037855,-66.233438,-70.687697,-73.564669,-73.463722,-72.605678
2,0.380228,0.950570,-0.253485,-1.394170,-5.196451,-8.986058,-8.998733,-11.533587,-8.567807,-15.335868,...,-62.737643,-62.801014,-63.852978,-64.765526,-66.970849,-71.444867,-74.334601,-74.233207,-73.371356,-71.077313
3,0.572519,-0.636132,-1.781170,-5.597964,-9.402036,-9.414758,-11.959288,-8.982188,-15.776081,-20.190840,...,-63.422392,-64.478372,-65.394402,-67.608142,-72.099237,-75.000000,-74.898219,-74.033079,-71.730280,-73.486005
4,-1.215611,-2.367242,-6.206014,-10.031990,-10.044786,-12.603967,-9.609725,-16.442738,-20.882917,-19.513756,...,-65.425464,-66.346769,-68.573257,-73.090211,-76.007678,-75.905310,-75.035189,-72.719130,-74.484965,-71.810621

In [ ]:
df4.shape

(6273, 5552)

In [ ]:
df5 = df4.dropna()

In [ ]:
df5.shape

(6185, 5552)

In [ ]:
len(df5[df5[7]>6])

730

In [ ]:
len(df5[df5[7]<2])

4509

In [ ]:
df6 = df5
df6 = df6.assign(result = lambda x: ((x['Close'] - x['Xth'])/x['Xth']*100)>reward)
    
df6['result'].value_counts()

False    3628
True     2557
Name: result, dtype: int64

In [ ]:
for i in range(len(df6.result)):
    if df6['result'][i] == False:
       df6['result'][i] = 0
    else:
       df6['result'][i] = 1

<ipython-input-26-04de6a8f24c2>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['result'][i] = 1

In [ ]:
df6.result.describe()

count     6185
unique       2
top          0
freq      3628
Name: result, dtype: int64

In [ ]:
df6.head()

,0,1,2,3,4,5,6,7,8,9,...,5543,5544,5545,5546,5547,5548,5549,Close,Xth,result
0,0.314465,0.754717,1.132075,1.698113,0.503145,-0.628931,-4.402516,-8.163522,-8.176101,-10.691824,...,7.397978,7.470721,6.357751,6.306831,4.342766,4.691933,4.357314,407.90,397.50,1
1,0.441640,0.820189,1.388013,0.189274,-0.946372,-4.731861,-8.504732,-8.517350,-11.041009,-8.088328,...,7.010746,5.892244,5.841070,3.867242,4.218145,3.881863,4.232766,406.25,396.25,1
2,0.380228,0.950570,-0.253485,-1.394170,-5.196451,-8.986058,-8.998733,-11.533587,-8.567807,-15.335868,...,4.630316,4.578456,2.578160,2.933768,2.592977,2.948585,1.600237,409.00,394.50,1
3,0.572519,-0.636132,-1.781170,-5.597964,-9.402036,-9.414758,-11.959288,-8.982188,-15.776081,-20.190840,...,5.544148,3.564095,3.916104,3.578762,3.930771,2.596069,1.730713,406.30,393.00,1
4,-1.215611,-2.367242,-6.206014,-10.031990,-10.044786,-12.603967,-9.609725,-16.442738,-20.882917,-19.513756,...,2.063007,2.420496,2.077903,2.435391,1.079914,0.201087,0.238326,401.50,390.75,1

In [ ]:
df7 = df6.drop(['Close','Xth'],axis=1)
df7.head()

,0,1,2,3,4,5,6,7,8,9,...,5541,5542,5543,5544,5545,5546,5547,5548,5549,result
0,0.314465,0.754717,1.132075,1.698113,0.503145,-0.628931,-4.402516,-8.163522,-8.176101,-10.691824,...,2.378701,5.724885,7.397978,7.470721,6.357751,6.306831,4.342766,4.691933,4.357314,1
1,0.441640,0.820189,1.388013,0.189274,-0.946372,-4.731861,-8.504732,-8.517350,-11.041009,-8.088328,...,5.256232,6.937642,7.010746,5.892244,5.841070,3.867242,4.218145,3.881863,4.232766,1
2,0.380228,0.950570,-0.253485,-1.394170,-5.196451,-8.986058,-8.998733,-11.533587,-8.567807,-15.335868,...,5.689732,5.763817,4.630316,4.578456,2.578160,2.933768,2.592977,2.948585,1.600237,1
3,0.572519,-0.636132,-1.781170,-5.597964,-9.402036,-9.414758,-11.959288,-8.982188,-15.776081,-20.190840,...,6.717512,5.595483,5.544148,3.564095,3.916104,3.578762,3.930771,2.596069,1.730713,1
4,-1.215611,-2.367242,-6.206014,-10.031990,-10.044786,-12.603967,-9.609725,-16.442738,-20.882917,-19.513756,...,4.126015,4.073881,2.063007,2.420496,2.077903,2.435391,1.079914,0.201087,0.238326,1

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline

In [ ]:
X = df7.drop('result',axis='columns')
y = df7["result"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [ ]:
X_train.shape

(4948, 5550)

In [ ]:
X_test.shape

(1237, 5550)

In [ ]:
aess = X_test.shape[1]

In [ ]:
import numpy as np

X_train1 = np.asarray(X_train).astype(np.float32)
X_test1 = np.asarray(X_test).astype(np.float32)
y_train1 = np.asarray(y_train).astype(np.float32)
y_test1 = np.asarray(y_test).astype(np.float32)

In [ ]:
import tensorflow as tf
from tensorflow import keras


model = keras.Sequential([
    keras.layers.Dense(aess, input_shape=(aess,), activation='sigmoid'),
    keras.layers.Dense(2000, activation='relu'),
    keras.layers.Dense(500, activation='relu'),
    keras.layers.Dense(120, activation='relu'),
    keras.layers.Dense(65, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# opt = keras.optimizers.Adam(learning_rate=0.01)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train1, y_train1, epochs=eps)

Epoch 1/200
155/155 [==============================] - 150s 956ms/step - loss: 0.7630 - accuracy: 0.5667
Epoch 2/200
155/155 [==============================] - 144s 927ms/step - loss: 0.6685 - accuracy: 0.5958
Epoch 3/200
155/155 [==============================] - 147s 948ms/step - loss: 0.6717 - accuracy: 0.5984
Epoch 4/200
155/155 [==============================] - 153s 988ms/step - loss: 0.6659 - accuracy: 0.6008
Epoch 5/200
155/155 [==============================] - 144s 930ms/step - loss: 0.6579 - accuracy: 0.6099
Epoch 6/200
155/155 [==============================] - 145s 935ms/step - loss: 0.6556 - accuracy: 0.6089
Epoch 7/200
155/155 [==============================] - 146s 946ms/step - loss: 0.6538 - accuracy: 0.6043
Epoch 8/200
155/155 [==============================] - 152s 983ms/step - loss: 0.6474 - accuracy: 0.6211
Epoch 9/200
155/155 [==============================] - 142s 918ms/step - loss: 0.6445 - accuracy: 0.6255
Epoch 10/200
155/155 [==============================] - 145s 935ms/step - loss: 0.6376 - accuracy: 0.6314
Epoch 11/200
155/155 [==============================] - 145s 935ms/step - loss: 0.6332 - accuracy: 0.6334
Epoch 12/200
155/155 [==============================] - 150s 967ms/step - loss: 0.6290 - accuracy: 0.6435
Epoch 13/200
155/155 [==============================] - 145s 939ms/step - loss: 0.6214 - accuracy: 0.6564
Epoch 14/200
155/155 [==============================] - 144s 932ms/step - loss: 0.6131 - accuracy: 0.6663
Epoch 15/200
155/155 [==============================] - 145s 934ms/step - loss: 0.6052 - accuracy: 0.6607
Epoch 16/200
155/155 [==============================] - 154s 994ms/step - loss: 0.6076 - accuracy: 0.6609
Epoch 17/200
155/155 [==============================] - 146s 940ms/step - loss: 0.5978 - accuracy: 0.6645
Epoch 18/200
155/155 [==============================] - 145s 935ms/step - loss: 0.5890 - accuracy: 0.6766
Epoch 19/200
155/155 [==============================] - 145s 931ms/step - loss: 0.5845 - accuracy: 0.6839
Epoch 20/200
155/155 [==============================] - 152s 981ms/step - loss: 0.5816 - accuracy: 0.6774
Epoch 21/200
155/155 [==============================] - 145s 934ms/step - loss: 0.5630 - accuracy: 0.6950
Epoch 22/200
155/155 [==============================] - 144s 928ms/step - loss: 0.5643 - accuracy: 0.6946
Epoch 23/200
155/155 [==============================] - 147s 946ms/step - loss: 0.5658 - accuracy: 0.6906
Epoch 24/200
155/155 [==============================] - 144s 931ms/step - loss: 0.5695 - accuracy: 0.6463
Epoch 25/200
155/155 [==============================] - 146s 938ms/step - loss: 0.5544 - accuracy: 0.7021
Epoch 26/200
155/155 [==============================] - 145s 939ms/step - loss: 0.5603 - accuracy: 0.7021
Epoch 27/200
155/155 [==============================] - 145s 931ms/step - loss: 0.5563 - accuracy: 0.7009
Epoch 28/200
155/155 [==============================] - 145s 939ms/step - loss: 0.5368 - accuracy: 0.7158
Epoch 29/200
155/155 [==============================] - 145s 934ms/step - loss: 0.5419 - accuracy: 0.7037
Epoch 30/200
155/155 [==============================] - 144s 930ms/step - loss: 0.5318 - accuracy: 0.7241
Epoch 31/200
155/155 [==============================] - 145s 939ms/step - loss: 0.5105 - accuracy: 0.7320
Epoch 32/200
155/155 [==============================] - 144s 929ms/step - loss: 0.5146 - accuracy: 0.7308
Epoch 33/200
155/155 [==============================] - 145s 934ms/step - loss: 0.5219 - accuracy: 0.7213
Epoch 34/200
155/155 [==============================] - 143s 925ms/step - loss: 0.5128 - accuracy: 0.7425
Epoch 35/200
155/155 [==============================] - 145s 932ms/step - loss: 0.5122 - accuracy: 0.7425
Epoch 36/200
155/155 [==============================] - 145s 938ms/step - loss: 0.5224 - accuracy: 0.7298
Epoch 37/200
155/155 [==============================] - 143s 926ms/step - loss: 0.4914 - accuracy: 0.7534
Epoch 38/200
155/155 [==============================] - 145s 937ms/step - loss: 0.5108 - accuracy: 0.7411
Epoch 39/200
155/155 [==============================] - 144s 930ms/step - loss: 0.4960 - accuracy: 0.7500
Epoch 40/200
155/155 [==============================] - 145s 935ms/step - loss: 0.5023 - accuracy: 0.7413
Epoch 41/200
155/155 [==============================] - 145s 939ms/step - loss: 0.4960 - accuracy: 0.7470
Epoch 42/200
155/155 [==============================] - 143s 925ms/step - loss: 0.4796 - accuracy: 0.7583
Epoch 43/200
155/155 [==============================] - 146s 940ms/step - loss: 0.4792 - accuracy: 0.7601
Epoch 44/200
155/155 [==============================] - 146s 942ms/step - loss: 0.4748 - accuracy: 0.7724
Epoch 45/200
155/155 [==============================] - 144s 926ms/step - loss: 0.4620 - accuracy: 0.7706
Epoch 46/200
155/155 [==============================] - 145s 936ms/step - loss: 0.4644 - accuracy: 0.7741
Epoch 47/200
155/155 [==============================] - 144s 928ms/step - loss: 0.4736 - accuracy: 0.7672
Epoch 48/200
155/155 [==============================] - 145s 936ms/step - loss: 0.4793 - accuracy: 0.7597
Epoch 49/200
155/155 [==============================] - 145s 936ms/step - loss: 0.4695 - accuracy: 0.7714
Epoch 50/200
155/155 [==============================] - 144s 928ms/step - loss: 0.4532 - accuracy: 0.7777
Epoch 51/200
155/155 [==============================] - 145s 938ms/step - loss: 0.4604 - accuracy: 0.7767
Epoch 52/200
155/155 [==============================] - 144s 930ms/step - loss: 0.4470 - accuracy: 0.7890
Epoch 53/200
155/155 [==============================] - 145s 936ms/step - loss: 0.4564 - accuracy: 0.7813
Epoch 54/200
155/155 [==============================] - 144s 932ms/step - loss: 0.4480 - accuracy: 0.7872
Epoch 55/200
155/155 [==============================] - 144s 928ms/step - loss: 0.4570 - accuracy: 0.7825
Epoch 56/200
155/155 [==============================] - 146s 940ms/step - loss: 0.4457 - accuracy: 0.7902
Epoch 57/200
155/155 [==============================] - 143s 924ms/step - loss: 0.4484 - accuracy: 0.7844
Epoch 58/200
155/155 [==============================] - 145s 936ms/step - loss: 0.4527 - accuracy: 0.7856
Epoch 59/200
155/155 [==============================] - 143s 921ms/step - loss: 0.4406 - accuracy: 0.7902
Epoch 60/200
155/155 [==============================] - 144s 933ms/step - loss: 0.4540 - accuracy: 0.7779
Epoch 61/200
155/155 [==============================] - 144s 930ms/step - loss: 0.4335 - accuracy: 0.7906
Epoch 62/200
155/155 [==============================] - 144s 928ms/step - loss: 0.4269 - accuracy: 0.7997
Epoch 63/200
155/155 [==============================] - 145s 937ms/step - loss: 0.4423 - accuracy: 0.7926
Epoch 64/200
155/155 [==============================] - 143s 924ms/step - loss: 0.4200 - accuracy: 0.8005
Epoch 65/200
155/155 [==============================] - 145s 935ms/step - loss: 0.4244 - accuracy: 0.7969
Epoch 66/200
155/155 [==============================] - 142s 919ms/step - loss: 0.4172 - accuracy: 0.8060
Epoch 67/200
155/155 [==============================] - 144s 931ms/step - loss: 0.4325 - accuracy: 0.8017
Epoch 68/200
155/155 [==============================] - 143s 920ms/step - loss: 0.4460 - accuracy: 0.7906
Epoch 69/200
155/155 [==============================] - 145s 935ms/step - loss: 0.4252 - accuracy: 0.8102
Epoch 70/200
155/155 [==============================] - 143s 923ms/step - loss: 0.4189 - accuracy: 0.8084
Epoch 71/200
155/155 [==============================] - 145s 934ms/step - loss: 0.4282 - accuracy: 0.8023
Epoch 72/200
155/155 [==============================] - 144s 928ms/step - loss: 0.4281 - accuracy: 0.7945
Epoch 73/200
155/155 [==============================] - 144s 925ms/step - loss: 0.4210 - accuracy: 0.8023
Epoch 74/200
155/155 [==============================] - 145s 934ms/step - loss: 0.4105 - accuracy: 0.8163
Epoch 75/200
155/155 [==============================] - 143s 922ms/step - loss: 0.4131 - accuracy: 0.8076
Epoch 76/200
155/155 [==============================] - 144s 932ms/step - loss: 0.4018 - accuracy: 0.8173
Epoch 77/200
155/155 [==============================] - 143s 925ms/step - loss: 0.3970 - accuracy: 0.8195
Epoch 78/200
155/155 [==============================] - 144s 927ms/step - loss: 0.4107 - accuracy: 0.8060
Epoch 79/200
155/155 [==============================] - 143s 925ms/step - loss: 0.4009 - accuracy: 0.8118
Epoch 80/200
155/155 [==============================] - 144s 924ms/step - loss: 0.4280 - accuracy: 0.7947
Epoch 81/200
155/155 [==============================] - 145s 934ms/step - loss: 0.4077 - accuracy: 0.8135
Epoch 82/200
155/155 [==============================] - 143s 921ms/step - loss: 0.3836 - accuracy: 0.8226
Epoch 83/200
155/155 [==============================] - 144s 932ms/step - loss: 0.3933 - accuracy: 0.8219
Epoch 84/200
155/155 [==============================] - 143s 920ms/step - loss: 0.3816 - accuracy: 0.8224
Epoch 85/200
155/155 [==============================] - 144s 932ms/step - loss: 0.3933 - accuracy: 0.8183
Epoch 86/200
155/155 [==============================] - 143s 922ms/step - loss: 0.3747 - accuracy: 0.8284
Epoch 87/200
155/155 [==============================] - 144s 931ms/step - loss: 0.3848 - accuracy: 0.8240
Epoch 88/200
155/155 [==============================] - 143s 924ms/step - loss: 0.4073 - accuracy: 0.8127
Epoch 89/200
155/155 [==============================] - 144s 928ms/step - loss: 0.3932 - accuracy: 0.8193
Epoch 90/200
155/155 [==============================] - 143s 921ms/step - loss: 0.3704 - accuracy: 0.8294
Epoch 91/200
155/155 [==============================] - 144s 930ms/step - loss: 0.3920 - accuracy: 0.8203
Epoch 92/200
155/155 [==============================] - 142s 920ms/step - loss: 0.3771 - accuracy: 0.8310
Epoch 93/200
155/155 [==============================] - 144s 930ms/step - loss: 0.3882 - accuracy: 0.8205
Epoch 94/200
155/155 [==============================] - 143s 926ms/step - loss: 0.3806 - accuracy: 0.8250
Epoch 95/200
155/155 [==============================] - 144s 928ms/step - loss: 0.3841 - accuracy: 0.8242
Epoch 96/200
155/155 [==============================] - 144s 928ms/step - loss: 0.3884 - accuracy: 0.8181
Epoch 97/200
155/155 [==============================] - 144s 925ms/step - loss: 0.3776 - accuracy: 0.8280
Epoch 98/200
155/155 [==============================] - 145s 935ms/step - loss: 0.3737 - accuracy: 0.8319
Epoch 99/200
155/155 [==============================] - 143s 921ms/step - loss: 0.3686 - accuracy: 0.8282
Epoch 100/200
155/155 [==============================] - 144s 932ms/step - loss: 0.3590 - accuracy: 0.8329
Epoch 101/200
155/155 [==============================] - 143s 920ms/step - loss: 0.3810 - accuracy: 0.8217
Epoch 102/200
 70/155 [============>.................] - ETA: 1:19 - loss: 0.3674 - accuracy: 0.8277

In [ ]:
model.evaluate(X_test1, y_test1)

NameError: ignored

In [ ]:
yp = model.predict(X_test)
yp[:5]

In [ ]:
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test1,y_pred))

In [ ]:
import seaborn as sn
cm = tf.math.confusion_matrix(labels=y_test1,predictions=y_pred)

plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')