In [85]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_csv("INFY.csv")
df.head(5)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,1996-01-01,INFOSYSTCH,EQ,408.00,407.0,407.9,405.00,NaN,407.90,406.48,400,1.625900e+10,NaN,NaN,NaN
1,1996-01-02,INFOSYSTCH,EQ,407.90,407.0,409.0,406.25,NaN,406.25,407.58,400,1.630300e+10,NaN,NaN,NaN
2,1996-01-03,INFOSYSTCH,EQ,406.25,409.0,409.0,409.00,NaN,409.00,409.00,200,8.180000e+09,NaN,NaN,NaN
3,1996-01-04,INFOSYSTCH,EQ,409.00,405.0,407.0,405.00,NaN,406.30,405.65,600,2.433900e+10,NaN,NaN,NaN
4,1996-01-05,INFOSYSTCH,EQ,406.30,401.5,401.5,401.50,NaN,401.50,401.50,100,4.015000e+09,NaN,NaN,NaN

In [87]:
df.columns

Index(['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last',
       'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume',
       '%Deliverble'],
      dtype='object')

In [88]:
df.dtypes

Date                   object
Symbol                 object
Series                 object
Prev Close            float64
Open                  float64
High                  float64
Low                   float64
Last                  float64
Close                 float64
VWAP                  float64
Volume                  int64
Turnover              float64
Trades                float64
Deliverable Volume    float64
%Deliverble           float64
dtype: object

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6348 entries, 0 to 6347
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                6348 non-null   object
 1   Symbol              6348 non-null   object
 2   Series              6348 non-null   object
 3   Prev Close          6348 non-null   float64
 4   Open                6348 non-null   float64
 5   High                6348 non-null   float64
 6   Low                 6348 non-null   float64
 7   Last                5802 non-null   float64
 8   Close               6348 non-null   float64
 9   VWAP                6348 non-null   float64
 10  Volume              6348 non-null   int64
 11  Turnover            6348 non-null   float64
 12  Trades              2501 non-null   float64
 13  Deliverable Volume  4843 non-null   float64
 14  %Deliverble         4843 non-null   float64
dtypes: float64(11), int64(1), object(3)
memory usage: 744.0+ KB

In [90]:
df1 = df[['Date','Close']]
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6348 entries, 0 to 6347
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6348 non-null   object
 1   Close   6348 non-null   float64
dtypes: float64(1), object(1)
memory usage: 99.3+ KB

In [91]:
df1.head(5)

         Date   Close
0  1996-01-01  407.90
1  1996-01-02  406.25
2  1996-01-03  409.00
3  1996-01-04  406.30
4  1996-01-05  401.50

In [92]:
c1 = []
for i in range(1,20):
    df['temp'] = df1['Close'] - df1['Close'].shift(-1*i)
    df['temp'] = df['temp']/df['Close']*100
    c1.append(df['temp'].to_numpy())

print(c1)    
df2 = pd.DataFrame(c1)
df3 = df2.transpose()
df3.head(10)

[array([ 0.40451091, -0.67692308,  0.6601467 , ..., -1.13560027,
        1.29048583,         nan]), array([-0.26967394, -0.01230769,  1.83374083, ...,  0.16954032,
               nan,         nan]), array([0.392253  , 1.16923077, 1.22249389, ...,        nan,        nan,
              nan]), array([1.56901201, 0.55384615, 2.32273839, ...,        nan,        nan,
              nan]), array([0.9561167 , 1.66153846, 3.17848411, ...,        nan,        nan,
              nan]), array([2.05932827, 2.52307692, 0.97799511, ...,        nan,        nan,
              nan]), array([2.91738171, 0.30769231, 1.52811736, ...,        nan,        nan,
              nan]), array([0.71095857, 0.86153846, 2.62836186, ...,        nan,        nan,
              nan]), array([1.26256435, 1.96923077, 2.200489  , ...,        nan,        nan,
              nan]), array([2.36577593, 1.53846154, 3.12958435, ...,        nan,        nan,
              nan]), array([1.9367492 , 2.47384615, 2.81173594, ...,        nan,        nan,
              nan]), array([2.86835009, 2.15384615, 3.78973105, ...,        nan,        nan,
              nan]), array([2.54964452, 3.13846154, 2.81173594, ...,        nan,        nan,
              nan]), array([3.53027703, 2.15384615, 3.11735941, ...,        nan,        nan,
              nan]), array([2.54964452, 2.46153846, 3.54523227, ...,        nan,        nan,
              nan]), array([2.85609218, 2.89230769, 3.91198044, ...,        nan,        nan,
              nan]), array([3.2851189 , 3.26153846, 4.46210269, ...,        nan,        nan,
              nan]), array([3.65285609, 3.81538462, 3.3007335 , ...,        nan,        nan,
              nan]), array([4.20446188, 2.64615385, 2.200489  , ...,        nan,        nan,
              nan])]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.404511,-0.269674,0.392253,1.569012,0.956117,2.059328,2.917382,0.710959,1.262564,2.365776,1.936749,2.868350,2.549645,3.530277,2.549645,2.856092,3.285119,3.652856,4.204462
1,-0.676923,-0.012308,1.169231,0.553846,1.661538,2.523077,0.307692,0.861538,1.969231,1.538462,2.473846,2.153846,3.138462,2.153846,2.461538,2.892308,3.261538,3.815385,2.646154
2,0.660147,1.833741,1.222494,2.322738,3.178484,0.977995,1.528117,2.628362,2.200489,3.129584,2.811736,3.789731,2.811736,3.117359,3.545232,3.911980,4.462103,3.300733,2.200489
3,1.181393,0.566084,1.673640,2.535073,0.319961,0.873739,1.981295,1.550578,2.485848,2.165887,3.150381,2.165887,2.473542,2.904258,3.273443,3.827221,2.658134,1.550578,-2.141275
4,-0.622665,0.498132,1.369863,-0.871731,-0.311333,0.809465,0.373599,1.320050,0.996264,1.992528,0.996264,1.307597,1.743462,2.117061,2.677460,1.494396,0.373599,-3.362391,-7.085928
5,1.113861,1.980198,-0.247525,0.309406,1.423267,0.990099,1.930693,1.608911,2.599010,1.608911,1.918317,2.351485,2.722772,3.279703,2.103960,0.990099,-2.722772,-6.423267,-6.435644
6,0.876095,-1.376721,-0.813517,0.312891,-0.125156,0.826033,0.500626,1.501877,0.500626,0.813517,1.251564,1.627034,2.190238,1.001252,-0.125156,-3.879850,-7.622028,-7.634543,-10.137672
7,-2.272727,-1.704545,-0.568182,-1.010101,-0.050505,-0.378788,0.631313,-0.378788,-0.063131,0.378788,0.757576,1.325758,0.126263,-1.010101,-4.797980,-8.573232,-8.585859,-11.111111,-8.156566
8,0.555556,1.666667,1.234568,2.172840,1.851852,2.839506,1.851852,2.160494,2.592593,2.962963,3.518519,2.345679,1.234568,-2.469136,-6.160494,-6.172840,-8.641975,-5.753086,-12.345679
9,1.117318,0.682806,1.626319,1.303538,2.296710,1.303538,1.613904,2.048417,2.420857,2.979516,1.800124,0.682806,-3.041589,-6.753569,-6.765984,-9.248914,-6.343886,-12.973309,-17.281192

In [93]:
df3.shape
print(len(c1))

19

In [94]:
c2 =df3.to_numpy()
c2

array([[ 0.40451091, -0.26967394,  0.392253  , ...,  3.2851189 ,
         3.65285609,  4.20446188],
       [-0.67692308, -0.01230769,  1.16923077, ...,  3.26153846,
         3.81538462,  2.64615385],
       [ 0.6601467 ,  1.83374083,  1.22249389, ...,  4.46210269,
         3.3007335 ,  2.200489  ],
       ...,
       [-1.13560027,  0.16954032,         nan, ...,         nan,
                nan,         nan],
       [ 1.29048583,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

In [95]:
len(c2)

6348

In [96]:
c3 =[]

for i in range(int(len(c2)-20)):
      
    c6 = np.concatenate((c2[i:i+20]))
    
    c3.append(c6)

In [97]:
c3[1:3]

[array([-6.76923077e-01, -1.23076923e-02,  1.16923077e+00,  5.53846154e-01,
         1.66153846e+00,  2.52307692e+00,  3.07692308e-01,  8.61538462e-01,
         1.96923077e+00,  1.53846154e+00,  2.47384615e+00,  2.15384615e+00,
         3.13846154e+00,  2.15384615e+00,  2.46153846e+00,  2.89230769e+00,
         3.26153846e+00,  3.81538462e+00,  2.64615385e+00,  6.60146699e-01,
         1.83374083e+00,  1.22249389e+00,  2.32273839e+00,  3.17848411e+00,
         9.77995110e-01,  1.52811736e+00,  2.62836186e+00,  2.20048900e+00,
         3.12958435e+00,  2.81173594e+00,  3.78973105e+00,  2.81173594e+00,
         3.11735941e+00,  3.54523227e+00,  3.91198044e+00,  4.46210269e+00,
         3.30073350e+00,  2.20048900e+00,  1.18139306e+00,  5.66084174e-01,
         1.67364017e+00,  2.53507261e+00,  3.19960620e-01,  8.73738617e-01,
         1.98129461e+00,  1.55057839e+00,  2.48584790e+00,  2.16588728e+00,
         3.15038149e+00,  2.16588728e+00,  2.47354172e+00,  2.90425794e+00,
         3.27344327e+00,  3.82722127e+00,  2.65813438e+00,  1.55057839e+00,
        -2.14127492e+00, -6.22665006e-01,  4.98132005e-01,  1.36986301e+00,
        -8.71731009e-01, -3.11332503e-01,  8.09464508e-01,  3.73599004e-01,
         1.32004981e+00,  9.96264010e-01,  1.99252802e+00,  9.96264010e-01,
         1.30759651e+00,  1.74346202e+00,  2.11706102e+00,  2.67745953e+00,
         1.49439601e+00,  3.73599004e-01, -3.36239103e+00, -7.08592777e+00,
         1.11386139e+00,  1.98019802e+00, -2.47524752e-01,  3.09405941e-01,
         1.42326733e+00,  9.90099010e-01,  1.93069307e+00,  1.60891089e+00,
         2.59900990e+00,  1.60891089e+00,  1.91831683e+00,  2.35148515e+00,
         2.72277228e+00,  3.27970297e+00,  2.10396040e+00,  9.90099010e-01,
        -2.72277228e+00, -6.42326733e+00, -6.43564356e+00,  8.76095119e-01,
        -1.37672090e+00, -8.13516896e-01,  3.12891114e-01, -1.25156446e-01,
         8.26032541e-01,  5.00625782e-01,  1.50187735e+00,  5.00625782e-01,
         8.13516896e-01,  1.25156446e+00,  1.62703379e+00,  2.19023780e+00,
         1.00125156e+00, -1.25156446e-01, -3.87984981e+00, -7.62202753e+00,
        -7.63454318e+00, -1.01376721e+01, -2.27272727e+00, -1.70454545e+00,
        -5.68181818e-01, -1.01010101e+00, -5.05050505e-02, -3.78787879e-01,
         6.31313131e-01, -3.78787879e-01, -6.31313131e-02,  3.78787879e-01,
         7.57575758e-01,  1.32575758e+00,  1.26262626e-01, -1.01010101e+00,
        -4.79797980e+00, -8.57323232e+00, -8.58585859e+00, -1.11111111e+01,
        -8.15656566e+00,  5.55555556e-01,  1.66666667e+00,  1.23456790e+00,
         2.17283951e+00,  1.85185185e+00,  2.83950617e+00,  1.85185185e+00,
         2.16049383e+00,  2.59259259e+00,  2.96296296e+00,  3.51851852e+00,
         2.34567901e+00,  1.23456790e+00, -2.46913580e+00, -6.16049383e+00,
        -6.17283951e+00, -8.64197531e+00, -5.75308642e+00, -1.23456790e+01,
         1.11731844e+00,  6.82805711e-01,  1.62631906e+00,  1.30353818e+00,
         2.29671012e+00,  1.30353818e+00,  1.61390441e+00,  2.04841713e+00,
         2.42085661e+00,  2.97951583e+00,  1.80012415e+00,  6.82805711e-01,
        -3.04158908e+00, -6.75356921e+00, -6.76598386e+00, -9.24891372e+00,
        -6.34388579e+00, -1.29733085e+01, -1.72811918e+01, -4.39422473e-01,
         5.14752040e-01,  1.88323917e-01,  1.19271814e+00,  1.88323917e-01,
         5.02197112e-01,  9.41619586e-01,  1.31826742e+00,  1.88323917e+00,
         6.90521030e-01, -4.39422473e-01, -4.20590082e+00, -7.95982423e+00,
        -7.97237916e+00, -1.04833647e+01, -7.54551161e+00, -1.42498431e+01,
        -1.86064030e+01, -1.72630257e+01,  9.50000000e-01,  6.25000000e-01,
         1.62500000e+00,  6.25000000e-01,  9.37500000e-01,  1.37500000e+00,
         1.75000000e+00,  2.31250000e+00,  1.12500000e+00,  0.00000000e+00,
        -3.75000000e+00, -7.48750000e+00, -7.50000000e+00, -1.00000000e+01,
        -7.07500000e+00, -1.37500000e+01, -1.80875000e+01, -1.67500000e+01,
        -2.25000000e+01, -3.28117113e-01,  6.81474003e-01, -3.28117113e-01,
        -1.26198889e-02,  4.29076224e-01,  8.07672892e-01,  1.37556790e+00,
         1.76678445e-01, -9.59111560e-01, -4.74507824e+00, -8.51842504e+00,
        -8.53104493e+00, -1.10550227e+01, -8.10196870e+00, -1.48409894e+01,
        -1.92200909e+01, -1.78697627e+01, -2.36749117e+01, -2.83442706e+01,
         1.00628931e+00,  0.00000000e+00,  3.14465409e-01,  7.54716981e-01,
         1.13207547e+00,  1.69811321e+00,  5.03144654e-01, -6.28930818e-01,
        -4.40251572e+00, -8.16352201e+00, -8.17610063e+00, -1.06918239e+01,
        -7.74842767e+00, -1.44654088e+01, -1.88301887e+01, -1.74842767e+01,
        -2.32704403e+01, -2.79245283e+01, -2.91320755e+01, -1.01651842e+00,
        -6.98856417e-01, -2.54129606e-01,  1.27064803e-01,  6.98856417e-01,
        -5.08259212e-01, -1.65184244e+00, -5.46378653e+00, -9.26302414e+00,
        -9.27573062e+00, -1.18170267e+01, -8.84371029e+00, -1.56289708e+01,
        -2.00381194e+01, -1.86785260e+01, -2.45235070e+01, -2.92249047e+01,
        -3.04447268e+01, -3.08132147e+01,  3.14465409e-01,  7.54716981e-01,
         1.13207547e+00,  1.69811321e+00,  5.03144654e-01, -6.28930818e-01,
        -4.40251572e+00, -8.16352201e+00, -8.17610063e+00, -1.06918239e+01,
        -7.74842767e+00, -1.44654088e+01, -1.88301887e+01, -1.74842767e+01,
        -2.32704403e+01, -2.79245283e+01, -2.91320755e+01, -2.94968553e+01,
        -2.68176101e+01,  4.41640379e-01,  8.20189274e-01,  1.38801262e+00,
         1.89274448e-01, -9.46372240e-01, -4.73186120e+00, -8.50473186e+00,
        -8.51735016e+00, -1.10410095e+01, -8.08832808e+00, -1.48264984e+01,
        -1.92050473e+01, -1.78548896e+01, -2.36593060e+01, -2.83280757e+01,
        -2.95394322e+01, -2.99053628e+01, -2.72176656e+01, -2.51987382e+01,
         3.80228137e-01,  9.50570342e-01, -2.53485425e-01, -1.39416984e+00,
        -5.19645120e+00, -8.98605830e+00, -8.99873257e+00, -1.15335868e+01,
        -8.56780735e+00, -1.53358682e+01, -1.97338403e+01, -1.83776933e+01,
        -2.42078580e+01, -2.88973384e+01, -3.01140684e+01, -3.04816223e+01,
        -2.77820025e+01, -2.57541191e+01, -2.47782003e+01,  5.72519084e-01,
        -6.36132316e-01, -1.78117048e+00, -5.59796438e+00, -9.40203562e+00,
        -9.41475827e+00, -1.19592875e+01, -8.98218830e+00, -1.57760814e+01,
        -2.01908397e+01, -1.88295165e+01, -2.46819338e+01, -2.93893130e+01,
        -3.06106870e+01, -3.09796438e+01, -2.82697201e+01, -2.62340967e+01,
        -2.52544529e+01, -2.64631043e+01, -1.21561100e+00, -2.36724248e+00,
        -6.20601408e+00, -1.00319898e+01, -1.00447857e+01, -1.26039667e+01,
        -9.60972489e+00, -1.64427383e+01, -2.08829175e+01, -1.95137556e+01,
        -2.53998720e+01, -3.01343570e+01, -3.13627639e+01, -3.17338452e+01,
        -2.90083173e+01, -2.69609725e+01, -2.59756878e+01, -2.71912988e+01,
        -2.79590531e+01, -1.13780025e+00, -4.93046776e+00, -8.71049305e+00,
        -8.72313527e+00, -1.12515803e+01, -8.29329962e+00, -1.50442478e+01,
        -1.94310999e+01, -1.80783818e+01, -2.38938053e+01, -2.85714286e+01,
        -2.97850822e+01, -3.01517067e+01, -2.74589128e+01, -2.54361568e+01,
        -2.44627054e+01, -2.56637168e+01, -2.64222503e+01, -2.01011378e+01]),
 array([ 6.60146699e-01,  1.83374083e+00,  1.22249389e+00,  2.32273839e+00,
         3.17848411e+00,  9.77995110e-01,  1.52811736e+00,  2.62836186e+00,
         2.20048900e+00,  3.12958435e+00,  2.81173594e+00,  3.78973105e+00,
         2.81173594e+00,  3.11735941e+00,  3.54523227e+00,  3.91198044e+00,
         4.46210269e+00,  3.30073350e+00,  2.20048900e+00,  1.18139306e+00,
         5.66084174e-01,  1.67364017e+00,  2.53507261e+00,  3.19960620e-01,
         8.73738617e-01,  1.98129461e+00,  1.55057839e+00,  2.48584790e+00,
         2.16588728e+00,  3.15038149e+00,  2.16588728e+00,  2.47354172e+00,
         2.90425794e+00,  3.27344327e+00,  3.82722127e+00,  2.65813438e+00,
         1.55057839e+00, -2.14127492e+00, -6.22665006e-01,  4.98132005e-01,
         1.36986301e+00, -8.71731009e-01, -3.11332503e-01,  8.09464508e-01,
         3.73599004e-01,  1.32004981e+00,  9.96264010e-01,  1.99252802e+00,
         9.96264010e-01,  1.30759651e+00,  1.74346202e+00,  2.11706102e+00,
         2.67745953e+00,  1.49439601e+00,  3.73599004e-01, -3.36239103e+00,
        -7.08592777e+00,  1.11386139e+00,  1.98019802e+00, -2.47524752e-01,
         3.09405941e-01,  1.42326733e+00,  9.90099010e-01,  1.93069307e+00,
         1.60891089e+00,  2.59900990e+00,  1.60891089e+00,  1.91831683e+00,
         2.35148515e+00,  2.72277228e+00,  3.27970297e+00,  2.10396040e+00,
         9.90099010e-01, -2.72277228e+00, -6.42326733e+00, -6.43564356e+00,
         8.76095119e-01, -1.37672090e+00, -8.13516896e-01,  3.12891114e-01,
        -1.25156446e-01,  8.26032541e-01,  5.00625782e-01,  1.50187735e+00,
         5.00625782e-01,  8.13516896e-01,  1.25156446e+00,  1.62703379e+00,
         2.19023780e+00,  1.00125156e+00, -1.25156446e-01, -3.87984981e+00,
        -7.62202753e+00, -7.63454318e+00, -1.01376721e+01, -2.27272727e+00,
        -1.70454545e+00, -5.68181818e-01, -1.01010101e+00, -5.05050505e-02,
        -3.78787879e-01,  6.31313131e-01, -3.78787879e-01, -6.31313131e-02,
         3.78787879e-01,  7.57575758e-01,  1.32575758e+00,  1.26262626e-01,
        -1.01010101e+00, -4.79797980e+00, -8.57323232e+00, -8.58585859e+00,
        -1.11111111e+01, -8.15656566e+00,  5.55555556e-01,  1.66666667e+00,
         1.23456790e+00,  2.17283951e+00,  1.85185185e+00,  2.83950617e+00,
         1.85185185e+00,  2.16049383e+00,  2.59259259e+00,  2.96296296e+00,
         3.51851852e+00,  2.34567901e+00,  1.23456790e+00, -2.46913580e+00,
        -6.16049383e+00, -6.17283951e+00, -8.64197531e+00, -5.75308642e+00,
        -1.23456790e+01,  1.11731844e+00,  6.82805711e-01,  1.62631906e+00,
         1.30353818e+00,  2.29671012e+00,  1.30353818e+00,  1.61390441e+00,
         2.04841713e+00,  2.42085661e+00,  2.97951583e+00,  1.80012415e+00,
         6.82805711e-01, -3.04158908e+00, -6.75356921e+00, -6.76598386e+00,
        -9.24891372e+00, -6.34388579e+00, -1.29733085e+01, -1.72811918e+01,
        -4.39422473e-01,  5.14752040e-01,  1.88323917e-01,  1.19271814e+00,
         1.88323917e-01,  5.02197112e-01,  9.41619586e-01,  1.31826742e+00,
         1.88323917e+00,  6.90521030e-01, -4.39422473e-01, -4.20590082e+00,
        -7.95982423e+00, -7.97237916e+00, -1.04833647e+01, -7.54551161e+00,
        -1.42498431e+01, -1.86064030e+01, -1.72630257e+01,  9.50000000e-01,
         6.25000000e-01,  1.62500000e+00,  6.25000000e-01,  9.37500000e-01,
         1.37500000e+00,  1.75000000e+00,  2.31250000e+00,  1.12500000e+00,
         0.00000000e+00, -3.75000000e+00, -7.48750000e+00, -7.50000000e+00,
        -1.00000000e+01, -7.07500000e+00, -1.37500000e+01, -1.80875000e+01,
        -1.67500000e+01, -2.25000000e+01, -3.28117113e-01,  6.81474003e-01,
        -3.28117113e-01, -1.26198889e-02,  4.29076224e-01,  8.07672892e-01,
         1.37556790e+00,  1.76678445e-01, -9.59111560e-01, -4.74507824e+00,
        -8.51842504e+00, -8.53104493e+00, -1.10550227e+01, -8.10196870e+00,
        -1.48409894e+01, -1.92200909e+01, -1.78697627e+01, -2.36749117e+01,
        -2.83442706e+01,  1.00628931e+00,  0.00000000e+00,  3.14465409e-01,
         7.54716981e-01,  1.13207547e+00,  1.69811321e+00,  5.03144654e-01,
        -6.28930818e-01, -4.40251572e+00, -8.16352201e+00, -8.17610063e+00,
        -1.06918239e+01, -7.74842767e+00, -1.44654088e+01, -1.88301887e+01,
        -1.74842767e+01, -2.32704403e+01, -2.79245283e+01, -2.91320755e+01,
        -1.01651842e+00, -6.98856417e-01, -2.54129606e-01,  1.27064803e-01,
         6.98856417e-01, -5.08259212e-01, -1.65184244e+00, -5.46378653e+00,
        -9.26302414e+00, -9.27573062e+00, -1.18170267e+01, -8.84371029e+00,
        -1.56289708e+01, -2.00381194e+01, -1.86785260e+01, -2.45235070e+01,
        -2.92249047e+01, -3.04447268e+01, -3.08132147e+01,  3.14465409e-01,
         7.54716981e-01,  1.13207547e+00,  1.69811321e+00,  5.03144654e-01,
        -6.28930818e-01, -4.40251572e+00, -8.16352201e+00, -8.17610063e+00,
        -1.06918239e+01, -7.74842767e+00, -1.44654088e+01, -1.88301887e+01,
        -1.74842767e+01, -2.32704403e+01, -2.79245283e+01, -2.91320755e+01,
        -2.94968553e+01, -2.68176101e+01,  4.41640379e-01,  8.20189274e-01,
         1.38801262e+00,  1.89274448e-01, -9.46372240e-01, -4.73186120e+00,
        -8.50473186e+00, -8.51735016e+00, -1.10410095e+01, -8.08832808e+00,
        -1.48264984e+01, -1.92050473e+01, -1.78548896e+01, -2.36593060e+01,
        -2.83280757e+01, -2.95394322e+01, -2.99053628e+01, -2.72176656e+01,
        -2.51987382e+01,  3.80228137e-01,  9.50570342e-01, -2.53485425e-01,
        -1.39416984e+00, -5.19645120e+00, -8.98605830e+00, -8.99873257e+00,
        -1.15335868e+01, -8.56780735e+00, -1.53358682e+01, -1.97338403e+01,
        -1.83776933e+01, -2.42078580e+01, -2.88973384e+01, -3.01140684e+01,
        -3.04816223e+01, -2.77820025e+01, -2.57541191e+01, -2.47782003e+01,
         5.72519084e-01, -6.36132316e-01, -1.78117048e+00, -5.59796438e+00,
        -9.40203562e+00, -9.41475827e+00, -1.19592875e+01, -8.98218830e+00,
        -1.57760814e+01, -2.01908397e+01, -1.88295165e+01, -2.46819338e+01,
        -2.93893130e+01, -3.06106870e+01, -3.09796438e+01, -2.82697201e+01,
        -2.62340967e+01, -2.52544529e+01, -2.64631043e+01, -1.21561100e+00,
        -2.36724248e+00, -6.20601408e+00, -1.00319898e+01, -1.00447857e+01,
        -1.26039667e+01, -9.60972489e+00, -1.64427383e+01, -2.08829175e+01,
        -1.95137556e+01, -2.53998720e+01, -3.01343570e+01, -3.13627639e+01,
        -3.17338452e+01, -2.90083173e+01, -2.69609725e+01, -2.59756878e+01,
        -2.71912988e+01, -2.79590531e+01, -1.13780025e+00, -4.93046776e+00,
        -8.71049305e+00, -8.72313527e+00, -1.12515803e+01, -8.29329962e+00,
        -1.50442478e+01, -1.94310999e+01, -1.80783818e+01, -2.38938053e+01,
        -2.85714286e+01, -2.97850822e+01, -3.01517067e+01, -2.74589128e+01,
        -2.54361568e+01, -2.44627054e+01, -2.56637168e+01, -2.64222503e+01,
        -2.01011378e+01, -3.75000000e+00, -7.48750000e+00, -7.50000000e+00,
        -1.00000000e+01, -7.07500000e+00, -1.37500000e+01, -1.80875000e+01,
        -1.67500000e+01, -2.25000000e+01, -2.71250000e+01, -2.83250000e+01,
        -2.86875000e+01, -2.60250000e+01, -2.40250000e+01, -2.30625000e+01,
        -2.42500000e+01, -2.50000000e+01, -1.87500000e+01, -1.90000000e+01])]

In [98]:
df4 = pd.DataFrame(c3)
df4.head(10)

,0,1,2,3,4,5,6,7,8,9,...,370,371,372,373,374,375,376,377,378,379
0,0.404511,-0.269674,0.392253,1.569012,0.956117,2.059328,2.917382,0.710959,1.262564,2.365776,...,-19.513756,-25.399872,-30.134357,-31.362764,-31.733845,-29.008317,-26.960972,-25.975688,-27.191299,-27.959053
1,-0.676923,-0.012308,1.169231,0.553846,1.661538,2.523077,0.307692,0.861538,1.969231,1.538462,...,-23.893805,-28.571429,-29.785082,-30.151707,-27.458913,-25.436157,-24.462705,-25.663717,-26.422250,-20.101138
2,0.660147,1.833741,1.222494,2.322738,3.178484,0.977995,1.528117,2.628362,2.200489,3.129584,...,-27.125000,-28.325000,-28.687500,-26.025000,-24.025000,-23.062500,-24.250000,-25.000000,-18.750000,-19.000000
3,1.181393,0.566084,1.673640,2.535073,0.319961,0.873739,1.981295,1.550578,2.485848,2.165887,...,-23.686747,-24.036145,-21.469880,-19.542169,-18.614458,-19.759036,-20.481928,-14.457831,-14.698795,-13.012048
4,-0.622665,0.498132,1.369863,-0.871731,-0.311333,0.809465,0.373599,1.320050,0.996264,1.992528,...,-19.723224,-17.246191,-15.385510,-14.490057,-15.594837,-16.292592,-10.477963,-10.710548,-9.082451,-9.896500
5,1.113861,1.980198,-0.247525,0.309406,1.423267,0.990099,1.930693,1.608911,2.599010,1.608911,...,-17.232558,-15.372093,-14.476744,-15.581395,-16.279070,-10.465116,-10.697674,-9.069767,-9.883721,-11.627907
6,0.876095,-1.376721,-0.813517,0.312891,-0.125156,0.826033,0.500626,1.501877,0.500626,0.813517,...,-12.750000,-11.875000,-12.954545,-13.636364,-7.954545,-8.181818,-6.590909,-7.386364,-9.090909,-6.022727
7,-2.272727,-1.704545,-0.568182,-1.010101,-0.050505,-0.378788,0.631313,-0.378788,-0.063131,0.378788,...,-14.931123,-16.040159,-16.740602,-10.903572,-11.137053,-9.502685,-10.319869,-12.070978,-8.918982,-12.070978
8,0.555556,1.666667,1.234568,2.172840,1.851852,2.839506,1.851852,2.160494,2.592593,2.962963,...,-9.230769,-9.890110,-4.395604,-4.615385,-3.076923,-3.846154,-5.494505,-2.527473,-5.494505,-6.362637
9,1.117318,0.682806,1.626319,1.303538,2.296710,1.303538,1.613904,2.048417,2.420857,2.979516,...,-5.853710,-0.561025,-0.772732,0.709220,-0.031756,-1.619562,1.238488,-1.619562,-2.455806,-1.407854

In [99]:
df3.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.404511,-0.269674,0.392253,1.569012,0.956117,2.059328,2.917382,0.710959,1.262564,2.365776,1.936749,2.868350,2.549645,3.530277,2.549645,2.856092,3.285119,3.652856,4.204462
1,-0.676923,-0.012308,1.169231,0.553846,1.661538,2.523077,0.307692,0.861538,1.969231,1.538462,2.473846,2.153846,3.138462,2.153846,2.461538,2.892308,3.261538,3.815385,2.646154
2,0.660147,1.833741,1.222494,2.322738,3.178484,0.977995,1.528117,2.628362,2.200489,3.129584,2.811736,3.789731,2.811736,3.117359,3.545232,3.911980,4.462103,3.300733,2.200489
3,1.181393,0.566084,1.673640,2.535073,0.319961,0.873739,1.981295,1.550578,2.485848,2.165887,3.150381,2.165887,2.473542,2.904258,3.273443,3.827221,2.658134,1.550578,-2.141275
4,-0.622665,0.498132,1.369863,-0.871731,-0.311333,0.809465,0.373599,1.320050,0.996264,1.992528,0.996264,1.307597,1.743462,2.117061,2.677460,1.494396,0.373599,-3.362391,-7.085928

In [100]:
df4.shape

(6328, 380)

In [101]:
df5 = df4.dropna()

In [102]:
df5.shape

(6310, 380)

In [103]:
len(df5[df5[7]>6])

732

In [104]:
len(df5[df5[7]<2])

4603

In [105]:
df6 = df5
df6 = df6.assign(result = lambda x: x[7]>6)
    
df6['result'].value_counts()

False    5578
True      732
Name: result, dtype: int64

In [106]:
for i in range(len(df6.result)):
    if df6['result'][i] == False:
       df6['result'][i] = 0
    else:
       df6['result'][i] = 1

C:\Users\abhij\AppData\Local\Temp\ipykernel_23548\4073025108.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6['result'][i] = 0

In [107]:
df6.result.describe()

count     6310
unique       2
top          0
freq      5578
Name: result, dtype: int64